# Generated by Django 5.2.7 on 2025-11-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(default='', upload_to='resources/'),
            preserve_default=False,
        ),
    ]
