# Generated by Django 5.2.7 on 2025-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_resource_description_remove_resource_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil'), ('EE', 'Electrical')], default='CSE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('sessional', 'Sessional Papers'), ('pyq', 'AKTU PYQs'), ('other', 'Other')], default='Notes', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(default='Maths', max_length=100),
            preserve_default=False,
        ),
    ]
